spring:
  kafka:    
    bootstrap-servers:
    - 15.164.117.97:9092    
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest  